insert into HOTEL_LOCATION VALUES(205,'SHANGHAI',' Chenghuangmiao Old Street',1.2),
	(206,'SHANGHAI',' Chenghuangmiao Old Street',1.3),
	(207,'SHANGHAI',' Chenghuangmiao Old Street',1.4),
	(208,'SHANGHAI',' Chenghuangmiao Old Street',1.3),
	(209,'SHANGHAI',' Chenghuangmiao Old Street',1.4),
	(210,'SHANGHAI',' Chenghuangmiao Old Street',1.4),
	(211,'SHANGHAI',' Chenghuangmiao Old Street',2.3),
	(212,'SHANGHAI',' Chenghuangmiao Old Street',2.2),
	(213,'SHANGHAI',' Chenghuangmiao Old Street',2.0),
	(214,'SHANGHAI',' Chenghuangmiao Old Street',2.0),
	(215,'SHANGHAI',' Chenghuangmiao Old Street',2.0),
	(216,'SHANGHAI',' Chenghuangmiao Old Street',2.8),
	(217,'SHANGHAI',' Chenghuangmiao Old Street',2.8),
	(218,'SHANGHAI',' Chenghuangmiao Old Street',2.7),
	(219,'SHANGHAI',' Chenghuangmiao Old Street',2.6),
	(220,'SHANGHAI',' Chenghuangmiao Old Street',2.5),
	(221,'SHANGHAI',' Chenghuangmiao Old Street',2.5),
	(222,'SHANGHAI',' Chenghuangmiao Old Street',2.4),
	(223,'SHANGHAI',' Chenghuangmiao Old Street',2.2),
	(224,'SHANGHAI',' Chenghuangmiao Old Street',2.2),
	(225,'SHANGHAI',' Chenghuangmiao Old Street',2.2),
	(226,'SHANGHAI',' Chenghuangmiao Old Street',1.2),
	(227,'SHANGHAI',' Chenghuangmiao Old Street',5.2),
	(228,'SHANGHAI',' Chenghuangmiao Old Street',5.2),
	(229,'SHANGHAI',' Chenghuangmiao Old Street',5.2),
	(230,'SHANGHAI',' Chenghuangmiao Old Street',5.2),
	(231,'SHANGHAI',' Chenghuangmiao Old Street',5.2),
	(232,'SHANGHAI',' Chenghuangmiao Old Street',5.3),
	(233,'SHANGHAI',' Chenghuangmiao Old Street',5.4),
	(234,'SHANGHAI',' Chenghuangmiao Old Street',2.5),
	(235,'SHANGHAI',' Chenghuangmiao Old Street',5.6),
	(236,'SHANGHAI',' Chenghuangmiao Old Street',5.6),
	(237,'SHANGHAI',' Chenghuangmiao Old Street',5.6),
	(238,'SHANGHAI',' Chenghuangmiao Old Street',1.6);

insert into HOTEL_LOCATION VALUES(205,'SHANGHAI',' Wujiang Road Food Street',3.2),
	(206,'SHANGHAI',' Wujiang Road Food Street',3.3),
	(207,'SHANGHAI',' Wujiang Road Food Street',3.4),
	(208,'SHANGHAI',' Wujiang Road Food Street',3.3),
	(209,'SHANGHAI',' Wujiang Road Food Street',2.4),
	(210,'SHANGHAI',' Wujiang Road Food Street',2.4),
	(211,'SHANGHAI',' Wujiang Road Food Street',1.3),
	(212,'SHANGHAI',' Wujiang Road Food Street',1.2),
	(213,'SHANGHAI',' Wujiang Road Food Street',1.0),
	(214,'SHANGHAI',' Wujiang Road Food Street',1.0),
	(215,'SHANGHAI',' Wujiang Road Food Street',1.0),
	(216,'SHANGHAI',' Wujiang Road Food Street',1.8),
	(217,'SHANGHAI',' Wujiang Road Food Street',1.8),
	(218,'SHANGHAI',' Wujiang Road Food Street',1.7),
	(219,'SHANGHAI',' Wujiang Road Food Street',3.6),
	(220,'SHANGHAI',' Wujiang Road Food Street',4.5),
	(221,'SHANGHAI',' Wujiang Road Food Street',5.5),
	(222,'SHANGHAI',' Wujiang Road Food Street',3.4),
	(223,'SHANGHAI',' Wujiang Road Food Street',2.2),
	(224,'SHANGHAI',' Wujiang Road Food Street',2.2),
	(225,'SHANGHAI',' Wujiang Road Food Street',2.2),
	(226,'SHANGHAI',' Wujiang Road Food Street',1.2),
	(227,'SHANGHAI',' Wujiang Road Food Street',2.2),
	(228,'SHANGHAI',' Wujiang Road Food Street',2.2),
	(229,'SHANGHAI',' Wujiang Road Food Street',3.2),
	(230,'SHANGHAI',' Wujiang Road Food Street',4.2),
	(231,'SHANGHAI',' Wujiang Road Food Street',5.2),
	(232,'SHANGHAI',' Wujiang Road Food Street',6.3),
	(233,'SHANGHAI',' Wujiang Road Food Street',2.4),
	(234,'SHANGHAI',' Wujiang Road Food Street',3.5),
	(235,'SHANGHAI',' Wujiang Road Food Street',5.6),
	(236,'SHANGHAI',' Wujiang Road Food Street',3.6),
	(237,'SHANGHAI',' Wujiang Road Food Street',1.6),
	(238,'SHANGHAI',' Wujiang Road Food Street',6.6);
insert into HOTEL_LOCATION VALUES(205,'SHANGHAI','Oriental Pearl Tower',2.2),
	(206,'SHANGHAI','Oriental Pearl Tower',0.3),
	(207,'SHANGHAI','Oriental Pearl Tower',0.4),
	(208,'SHANGHAI','Oriental Pearl Tower',0.3),
	(209,'SHANGHAI','Oriental Pearl Tower',0.4),
	(210,'SHANGHAI','Oriental Pearl Tower',0.4),
	(211,'SHANGHAI','Oriental Pearl Tower',1.3),
	(212,'SHANGHAI','Oriental Pearl Tower',1.2),
	(213,'SHANGHAI','Oriental Pearl Tower',1.0),
	(214,'SHANGHAI','Oriental Pearl Tower',1.0),
	(215,'SHANGHAI','Oriental Pearl Tower',1.0),
	(216,'SHANGHAI','Oriental Pearl Tower',1.8),
	(217,'SHANGHAI','Oriental Pearl Tower',1.8),
	(218,'SHANGHAI','Oriental Pearl Tower',2.7),
	(219,'SHANGHAI','Oriental Pearl Tower',2.6),
	(220,'SHANGHAI','Oriental Pearl Tower',3.5),
	(221,'SHANGHAI','Oriental Pearl Tower',2.5),
	(222,'SHANGHAI','Oriental Pearl Tower',1.4),
	(223,'SHANGHAI','Oriental Pearl Tower',1.2),
	(224,'SHANGHAI','Oriental Pearl Tower',2.2),
	(225,'SHANGHAI','Oriental Pearl Tower',3.2),
	(226,'SHANGHAI','Oriental Pearl Tower',1.2),
	(227,'SHANGHAI','Oriental Pearl Tower',2.2),
	(228,'SHANGHAI','Oriental Pearl Tower',1.2),
	(229,'SHANGHAI','Oriental Pearl Tower',1.2),
	(230,'SHANGHAI','Oriental Pearl Tower',1.2),
	(231,'SHANGHAI','Oriental Pearl Tower',1.2),
	(232,'SHANGHAI','Oriental Pearl Tower',1.3),
	(233,'SHANGHAI','Oriental Pearl Tower',2.4),
	(234,'SHANGHAI','Oriental Pearl Tower',3.5),
	(235,'SHANGHAI','Oriental Pearl Tower',1.6),
	(236,'SHANGHAI','Oriental Pearl Tower',3.6),
	(237,'SHANGHAI','Oriental Pearl Tower',3.6),
	(238,'SHANGHAI','Oriental Pearl Tower',3.6);

insert into HOTEL_LOCATION VALUES(205,'SHANGHAI','Shanghai Museum',2.2),
	(206,'SHANGHAI','Shanghai Museum',0.7),
	(207,'SHANGHAI','Shanghai Museum',0.7),
	(208,'SHANGHAI','Shanghai Museum',0.6),
	(209,'SHANGHAI','Shanghai Museum',0.8),
	(210,'SHANGHAI','Shanghai Museum',0.6),
	(211,'SHANGHAI','Shanghai Museum',1.7),
	(212,'SHANGHAI','Shanghai Museum',1.6),
	(213,'SHANGHAI','Shanghai Museum',1.7),
	(214,'SHANGHAI','Shanghai Museum',1.7),
	(215,'SHANGHAI','Shanghai Museum',1.7),
	(216,'SHANGHAI','Shanghai Museum',1.6),
	(217,'SHANGHAI','Shanghai Museum',1.7),
	(218,'SHANGHAI','Shanghai Museum',2.7),
	(219,'SHANGHAI','Shanghai Museum',2.6),
	(220,'SHANGHAI','Shanghai Museum',3.7),
	(221,'SHANGHAI','Shanghai Museum',2.7),
	(222,'SHANGHAI','Shanghai Museum',1.8),
	(223,'SHANGHAI','Shanghai Museum',1.9),
	(224,'SHANGHAI','Shanghai Museum',3.2),
	(225,'SHANGHAI','Shanghai Museum',3.2),
	(226,'SHANGHAI','Shanghai Museum',3.2),
	(227,'SHANGHAI','Shanghai Museum',2.2),
	(228,'SHANGHAI','Shanghai Museum',3.2),
	(229,'SHANGHAI','Shanghai Museum',3.2),
	(230,'SHANGHAI','Shanghai Museum',1.2),
	(231,'SHANGHAI','Shanghai Museum',1.2),
	(232,'SHANGHAI','Shanghai Museum',3.3),
	(233,'SHANGHAI','Shanghai Museum',2.4),
	(234,'SHANGHAI','Shanghai Museum',3.5),
	(235,'SHANGHAI','Shanghai Museum',1.6),
	(236,'SHANGHAI','Shanghai Museum',1.6),
	(237,'SHANGHAI','Shanghai Museum',3.6),
	(238,'SHANGHAI','Shanghai Museum',1.6);
insert into HOTEL_LOCATION VALUES(205,'SHANGHAI','jin mao tower shanghai',1.2),
	(206,'SHANGHAI','jin mao tower shanghai',0.4),
	(207,'SHANGHAI','jin mao tower shanghai',0.3),
	(208,'SHANGHAI','jin mao tower shanghai',0.3),
	(209,'SHANGHAI','jin mao tower shanghai',0.3),
	(210,'SHANGHAI','jin mao tower shanghai',0.3),
	(211,'SHANGHAI','jin mao tower shanghai',1.3),
	(212,'SHANGHAI','jin mao tower shanghai',1.3),
	(213,'SHANGHAI','jin mao tower shanghai',1.1),
	(214,'SHANGHAI','jin mao tower shanghai',1.2),
	(215,'SHANGHAI','jin mao tower shanghai',1.7),
	(216,'SHANGHAI','jin mao tower shanghai',3.6),
	(217,'SHANGHAI','jin mao tower shanghai',3.7),
	(218,'SHANGHAI','jin mao tower shanghai',3.7),
	(219,'SHANGHAI','jin mao tower shanghai',3.6),
	(220,'SHANGHAI','jin mao tower shanghai',3.7),
	(221,'SHANGHAI','jin mao tower shanghai',2.7),
	(222,'SHANGHAI','jin mao tower shanghai',1.8),
	(223,'SHANGHAI','jin mao tower shanghai',1.9),
	(224,'SHANGHAI','jin mao tower shanghai',1.2),
	(225,'SHANGHAI','jin mao tower shanghai',3.2),
	(226,'SHANGHAI','jin mao tower shanghai',3.2),
	(227,'SHANGHAI','jin mao tower shanghai',3.2),
	(228,'SHANGHAI','jin mao tower shanghai',3.2),
	(229,'SHANGHAI','jin mao tower shanghai',1.2),
	(230,'SHANGHAI','jin mao tower shanghai',3.2),
	(231,'SHANGHAI','jin mao tower shanghai',1.2),
	(232,'SHANGHAI','jin mao tower shanghai',3.3),
	(233,'SHANGHAI','jin mao tower shanghai',1.4),
	(234,'SHANGHAI','jin mao tower shanghai',3.5),
	(235,'SHANGHAI','jin mao tower shanghai',3.6),
	(236,'SHANGHAI','jin mao tower shanghai',1.6),
	(237,'SHANGHAI','jin mao tower shanghai',3.6),
	(238,'SHANGHAI','jin mao tower shanghai',2.6);

insert into HOTEL_LOCATION VALUES(205,'SHANGHAI','Shanghai World Financial Center',0.2),
	(206,'SHANGHAI','Shanghai World Financial Center',0.1),
	(207,'SHANGHAI','Shanghai World Financial Center',0.4),
	(208,'SHANGHAI','Shanghai World Financial Center',0.5),
	(209,'SHANGHAI','Shanghai World Financial Center',0.3),
	(210,'SHANGHAI','Shanghai World Financial Center',0.3),
	(211,'SHANGHAI','Shanghai World Financial Center',1.3),
	(212,'SHANGHAI','Shanghai World Financial Center',2.3),
	(213,'SHANGHAI','Shanghai World Financial Center',2.1),
	(214,'SHANGHAI','Shanghai World Financial Center',2.2),
	(215,'SHANGHAI','Shanghai World Financial Center',2.7),
	(216,'SHANGHAI','Shanghai World Financial Center',3.6),
	(217,'SHANGHAI','Shanghai World Financial Center',3.7),
	(218,'SHANGHAI','Shanghai World Financial Center',3.7),
	(219,'SHANGHAI','Shanghai World Financial Center',3.6),
	(220,'SHANGHAI','Shanghai World Financial Center',2.7),
	(221,'SHANGHAI','Shanghai World Financial Center',2.7),
	(222,'SHANGHAI','Shanghai World Financial Center',1.8),
	(223,'SHANGHAI','Shanghai World Financial Center',1.9),
	(224,'SHANGHAI','Shanghai World Financial Center',2.2),
	(225,'SHANGHAI','Shanghai World Financial Center',3.2),
	(226,'SHANGHAI','Shanghai World Financial Center',3.2),
	(227,'SHANGHAI','Shanghai World Financial Center',3.2),
	(228,'SHANGHAI','Shanghai World Financial Center',2.2),
	(229,'SHANGHAI','Shanghai World Financial Center',1.2),
	(230,'SHANGHAI','Shanghai World Financial Center',3.2),
	(231,'SHANGHAI','Shanghai World Financial Center',1.2),
	(232,'SHANGHAI','Shanghai World Financial Center',3.3),
	(233,'SHANGHAI','Shanghai World Financial Center',1.4),
	(234,'SHANGHAI','Shanghai World Financial Center',1.5),
	(235,'SHANGHAI','Shanghai World Financial Center',3.6),
	(236,'SHANGHAI','Shanghai World Financial Center',2.6),
	(237,'SHANGHAI','Shanghai World Financial Center',3.6),
	(238,'SHANGHAI','Shanghai World Financial Center',1.6);




