CREATE DATABASE trivago;
use trivago;
create table HOTEL(
ID_HOTEL INT(5) AUTO_INCREMENT PRIMARY KEY,
NAME_HOTEL VARCHAR(50) NOT NULL UNIQUE,
PRICE INT(5) NOT NULL,
REVIEW_RANK FLOAT(5) NOT NULL,
HOTEL_TYPE INT(5) NOT NULL,
CHECK(REVIEW_RANK>0 AND REVIEW_RANK<=0),
CHECK(HOTEL_TYPE>0 AND HOTEL_TYPE<6));
create table HOTEL_LOCATION(
ID_HOTEL INT(5),
NAME_CITY VARCHAR(50),
POPULAR_ADDRESS VARCHAR(50),
DISTANCE FLOAT(5) NOT NULL,
PRIMARY KEY(ID_HOTEL,NAME_CITY,POPULAR_ADDRESS),
CONSTRAINT fk0 FOREIGN KEY(ID_HOTEL) REFERENCES HOTEL(ID_HOTEL)
);
create table ROOM(
ID_HOTEL INT(5),
ID_ROOM INT(5),
ROOM_TYPE VARCHAR(50) NOT NULL,
CAPACITY INT(5) NOT NULL,
PRIMARY KEY(ID_HOTEL,ID_ROOM),
CONSTRAINT fk1 FOREIGN KEY (ID_HOTEL) REFERENCES HOTEL(ID_HOTEL)
);
create table ROOM_BOOKING(
ID_HOTEL INT(5),
ID_ROOM INT(5),
CHECK_IN DATE,
CHECK_OUT DATE NOT NULL,
PRIMARY KEY(ID_HOTEL,ID_ROOM,CHECK_IN),
CONSTRAINT fk2 FOREIGN KEY(ID_HOTEL,ID_ROOM) REFERENCES ROOM(ID_HOTEL,ID_ROOM)
);
create table PAY(
ID_HOTEL INT(5),
ID_PAY INT(5) NOT NULL,
NAME_PAY VARCHAR(100) NOT NULL,
CONSTRAINT fk3 FOREIGN key (ID_HOTEL) REFERENCES HOTEL(ID_HOTEL)
);
